FROM python:3.11-slim

WORKDIR /build

# Install zip (required to create lambda.zip)
RUN apt-get update && apt-get install -y zip && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -t .

# Copy main scripts
COPY lambda_function.py ./

# Remove unnecessary files
RUN find . -type d -name "__pycache__" -exec rm -rf {} + \
 && find . -type d -name "tests" -exec rm -rf {} + \
 && find . -type d -name "*.dist-info" -exec rm -rf {} + \
 && find . -type f -name "*.pyc" -delete


RUN zip -r lambda.zip .
