FROM public.ecr.aws/lambda/python:3.11

# Prevent Python from writing pyc files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Upgrade build tooling FIRST
RUN pip install --upgrade pip setuptools wheel

# Copy application code
COPY . ${LAMBDA_TASK_ROOT}

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Google service account keys
# COPY teams-maker-key.json .
# COPY players-db-key.json .

# Lambda entry point
CMD ["app.lambda_handler"]